### ISSUE TITLE
かぼちゃ豆乳入り瓶の注液及び排液レシピの欠落

### ISSUE THREAD

**Issue by Yurisan001** [baguchi/TofuCreate#1]
modバージョン0.1.0,minecraft1.19.2&1.20.1にて、かぼちゃ豆乳の混合レシピは存在しているのに注液レシピと排液レシピが存在しません
Jar内のfillingフォルダとemptyingフォルダ内のsoymilk_pumpkin.jsonが欠落しているため起きているようです

**Comment by baguchi** [comment]
修正しました！
